name: brykoch
favicon: null
layout_spectrum: 0.25018
typography_spectrum: 0.50175
title: Bryan Koch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71953855-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#615853'
    - '#292621'
    - '#a59890'
    - '#4a423f'
    - '#d3c7bb'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
