name: brykoch
favicon: null
layout_spectrum: 0.26722012157551944
typography_spectrum: 0.00957808387465775
title: Bryan Koch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71953855-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8970732563175261
  lightness: 0.05695010907948017
  saturation: 0.8207470867782831
  rhythmicContrast: 0.3932521450333297
purpose: []
